In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, Normalizer, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Lab | Customer Analysis Round 5

In [2]:
data = pd.read_csv('marketing_customer_analysis.csv')
data

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,23405.987980,No,Basic,Bachelor,2/10/11,Employed,M,71941,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,PK87824,California,3096.511217,Yes,Extended,College,2/12/11,Employed,F,21604,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,TD14365,California,8163.890428,No,Extended,Bachelor,2/6/11,Unemployed,M,0,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,UP19263,California,7524.442436,No,Extended,College,2/3/11,Employed,M,21941,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,Y167826,California,2611.836866,No,Extended,College,2/14/11,Unemployed,M,0,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [ ]:
#Copy

In [7]:
data1 = data.copy()

In [ ]:
#Numerical/categorical

In [8]:
data1.select_dtypes("object")

,Customer,State,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Location Code,Marital Status,Policy Type,Policy,Renew Offer Type,Sales Channel,Vehicle Class,Vehicle Size
0,BU79786,Washington,No,Basic,Bachelor,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,QZ44356,Arizona,No,Extended,Bachelor,1/31/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,AI49188,Nevada,No,Premium,Bachelor,2/19/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,WW63253,California,No,Basic,Bachelor,1/20/11,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,HB64268,Washington,No,Basic,Bachelor,2/3/11,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,No,Basic,Bachelor,2/10/11,Employed,M,Urban,Married,Personal Auto,Personal L1,Offer2,Web,Four-Door Car,Medsize
9130,PK87824,California,Yes,Extended,College,2/12/11,Employed,F,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
9131,TD14365,California,No,Extended,Bachelor,2/6/11,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,Medsize
9132,UP19263,California,No,Extended,College,2/3/11,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,Large
9133,Y167826,California,No,Extended,College,2/14/11,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,Medsize

In [9]:
data1.select_dtypes("number")

,Customer Lifetime Value,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount
0,2763.519279,56274,69,32,5,0,1,384.811147
1,6979.535903,0,94,13,42,0,8,1131.464935
2,12887.431650,48767,108,18,38,0,2,566.472247
3,7645.861827,0,106,18,65,0,7,529.881344
4,2813.692575,43836,73,12,44,0,1,138.130879
...,...,...,...,...,...,...,...,...
9129,23405.987980,71941,73,18,89,0,2,198.234764
9130,3096.511217,21604,79,14,28,0,1,379.200000
9131,8163.890428,0,85,9,37,3,2,790.784983
9132,7524.442436,21941,96,34,3,0,3,691.200000
9133,2611.836866,0,77,3,90,0,1,369.600000

In [ ]:
#X-y Split

In [10]:
X = data1.drop(["Response"], axis=1)
y = data["Response"]

In [ ]:
#Normalize numerical

In [13]:
scaler = StandardScaler()
scaler

StandardScaler()

In [14]:
numerical_cols = ['Customer Lifetime Value', 'Income', 'Monthly Premium Auto', 'Months Since Last Claim', 'Months Since Policy Inception', 'Number of Open Complaints', 'Number of Policies']
scaler = StandardScaler()
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

In [ ]:
#Lab | Customer Analysis Round 6

In [ ]:
#One Hot/Label Encoding (categorical)

In [16]:
categorical_cols = ['State', 'Coverage', 'Education', 'EmploymentStatus', 'Gender', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size']
categorical_cols

['State',
 'Coverage',
 'Education',
 'EmploymentStatus',
 'Gender',
 'Policy Type',
 'Policy',
 'Renew Offer Type',
 'Sales Channel',
 'Vehicle Class',
 'Vehicle Size']

In [17]:
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [18]:
X_encoded

,Customer,Customer Lifetime Value,Effective To Date,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,...,Sales Channel_Branch,Sales Channel_Call Center,Sales Channel_Web,Vehicle Class_Luxury Car,Vehicle Class_Luxury SUV,Vehicle Class_SUV,Vehicle Class_Sports Car,Vehicle Class_Two-Door Car,Vehicle Size_Medsize,Vehicle Size_Small
0,BU79786,-0.762878,2/24/11,0.612827,Suburban,Married,-0.703925,1.678099,-1.543287,-0.422250,...,0,0,0,0,0,0,0,1,1,0
1,QZ44356,-0.149245,1/31/11,-1.239617,Suburban,Single,0.022691,-0.208186,-0.217334,-0.422250,...,0,0,0,0,0,0,0,0,1,0
2,AI49188,0.710636,2/19/11,0.365710,Suburban,Married,0.429596,0.288205,-0.360680,-0.422250,...,0,0,0,0,0,0,0,1,1,0
3,WW63253,-0.052263,1/20/11,-1.239617,Suburban,Married,0.371467,0.288205,0.606907,-0.422250,...,0,1,0,0,0,1,0,0,1,0
4,HB64268,-0.755575,2/3/11,0.203390,Rural,Single,-0.587666,-0.307465,-0.145661,-0.422250,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,2.241590,2/10/11,1.128558,Urban,Married,-0.587666,0.288205,1.466984,-0.422250,...,0,0,1,0,0,0,0,0,1,0
9130,PK87824,-0.714411,2/12/11,-0.528450,Suburban,Divorced,-0.413278,-0.108908,-0.719046,-0.422250,...,1,0,0,0,0,0,0,0,1,0
9131,TD14365,0.023135,2/6/11,-1.239617,Suburban,Single,-0.238891,-0.605299,-0.396517,2.873245,...,1,0,0,0,0,0,0,0,1,0
9132,UP19263,-0.069935,2/3/11,-0.517356,Suburban,Married,0.080820,1.876656,-1.614960,-0.422250,...,1,0,0,0,0,0,0,0,0,0
9133,Y167826,-0.784955,2/14/11,-1.239617,Suburban,Single,-0.471408,-1.200968,1.502821,-0.422250,...,0,1,0,0,0,0,0,1,1,0

In [19]:
encoder = OneHotEncoder(drop='first')
encoder

OneHotEncoder(drop='first')

In [ ]:
#Concat DataFrames

In [20]:
concat = pd.concat([X_encoded, X[numerical_cols]], axis=1)

In [21]:
concat

,Customer,Customer Lifetime Value,Effective To Date,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,...,Vehicle Class_Two-Door Car,Vehicle Size_Medsize,Vehicle Size_Small,Customer Lifetime Value,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies
0,BU79786,-0.762878,2/24/11,0.612827,Suburban,Married,-0.703925,1.678099,-1.543287,-0.422250,...,1,1,0,-0.762878,0.612827,-0.703925,1.678099,-1.543287,-0.422250,-0.822648
1,QZ44356,-0.149245,1/31/11,-1.239617,Suburban,Single,0.022691,-0.208186,-0.217334,-0.422250,...,0,1,0,-0.149245,-1.239617,0.022691,-0.208186,-0.217334,-0.422250,2.106160
2,AI49188,0.710636,2/19/11,0.365710,Suburban,Married,0.429596,0.288205,-0.360680,-0.422250,...,1,1,0,0.710636,0.365710,0.429596,0.288205,-0.360680,-0.422250,-0.404247
3,WW63253,-0.052263,1/20/11,-1.239617,Suburban,Married,0.371467,0.288205,0.606907,-0.422250,...,0,1,0,-0.052263,-1.239617,0.371467,0.288205,0.606907,-0.422250,1.687759
4,HB64268,-0.755575,2/3/11,0.203390,Rural,Single,-0.587666,-0.307465,-0.145661,-0.422250,...,0,1,0,-0.755575,0.203390,-0.587666,-0.307465,-0.145661,-0.422250,-0.822648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,2.241590,2/10/11,1.128558,Urban,Married,-0.587666,0.288205,1.466984,-0.422250,...,0,1,0,2.241590,1.128558,-0.587666,0.288205,1.466984,-0.422250,-0.404247
9130,PK87824,-0.714411,2/12/11,-0.528450,Suburban,Divorced,-0.413278,-0.108908,-0.719046,-0.422250,...,0,1,0,-0.714411,-0.528450,-0.413278,-0.108908,-0.719046,-0.422250,-0.822648
9131,TD14365,0.023135,2/6/11,-1.239617,Suburban,Single,-0.238891,-0.605299,-0.396517,2.873245,...,0,1,0,0.023135,-1.239617,-0.238891,-0.605299,-0.396517,2.873245,-0.404247
9132,UP19263,-0.069935,2/3/11,-0.517356,Suburban,Married,0.080820,1.876656,-1.614960,-0.422250,...,0,0,0,-0.069935,-0.517356,0.080820,1.876656,-1.614960,-0.422250,0.014154
9133,Y167826,-0.784955,2/14/11,-1.239617,Suburban,Single,-0.471408,-1.200968,1.502821,-0.422250,...,1,1,0,-0.784955,-1.239617,-0.471408,-1.200968,1.502821,-0.422250,-0.822648

In [ ]:
#Train-test split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [26]:
y_train

434     Yes
4641     No
4952    Yes
1489     No
812      No
       ...
5734     No
5191    Yes
5390     No
860     Yes
7270     No
Name: Response, Length: 6393, dtype: object

In [ ]:
#Apply linear regression

In [38]:
scaler = StandardScaler()

In [40]:
scaler.fit(X_train)

ValueError: could not convert string to float: 'JY45873'

In [41]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: could not convert string to float: 'JY45873'

In [42]:
ln = LinearRegression()

In [43]:
ln.fit(X_train_scaled, y_train)

NameError: name 'X_train_scaled' is not defined

In [ ]:
#Model Validation
#Description: #R2. #MSE. #RMSE. #MAE.
#In summary, R2 serves as an indicator of the overall goodness of fit of a model, providing insight into
#how well the independent variables explain the dependent variable. On the other hand, RMSE and MAE focus 
#on the error between predicted and actual values. RMSE highlights larger errors more prominently, 
#while MAE treats all errors equally. It is important to consider these metrics in conjunction to gain 
#a comprehensive understanding of a model's performance and its ability to accurately predict the 
#dependent variable.